/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.view;
import dev.view.Impressao;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Wesle
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jCEP = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jNcasa = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTelefone = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jData = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jCupom = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPDV = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jProduto1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCodigo1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jQTD1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jProduto2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCodigo2 = new javax.swing.JTextField();
        jQTD2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jProduto3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jCodigo3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jQTD3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jProduto4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jCodigo4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jQTD4 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jProduto5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jCodigo5 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jQTD5 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonGerar = new javax.swing.JButton();
        jValor1 = new javax.swing.JTextField();
        jValor2 = new javax.swing.JTextField();
        jValor4 = new javax.swing.JTextField();
        jValor3 = new javax.swing.JTextField();
        jValor5 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("DADOS DO CLIENTE");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOME:");

        jNome.setText("Weslei de Jesus Pozar");
        jNome.setToolTipText("INSIRA O NOME AQUI");
        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });
        jNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNomeKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CPF:");

        try {
            jCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPF.setText("063.711.425-69");
        jCPF.setToolTipText("INSIRA O CPF");
        jCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPFActionPerformed(evt);
            }
        });
        jCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCPFKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CEP:");

        try {
            jCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCEP.setText("41.100.134");
        jCEP.setToolTipText("INSIRA O CEP");
        jCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEPActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("N°:");

        jNcasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jNcasa.setText("145");
        jNcasa.setToolTipText("");
        jNcasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNcasaActionPerformed(evt);
            }
        });
        jNcasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNcasaKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TEL:");

        try {
            jTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTelefone.setText("(71)9 8136-2060");
        jTelefone.setToolTipText("INSIRA O TELEFONE");

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("DATA COMPRA:");

        try {
            jData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jData.setText("26/05/2023");
        jData.setToolTipText("INSIRA O DATA");
        jData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CUPOM:");

        jCupom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jCupom.setText("458775");
        jCupom.setToolTipText("INSIRA O CUPOM");
        jCupom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCupomActionPerformed(evt);
            }
        });

        jPanel3.setPreferredSize(new java.awt.Dimension(4, 169));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("DADOS DA NOTA");

        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("PDV:");

        try {
            jPDV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPDV.setText("15");
        jPDV.setToolTipText("");
        jPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPDVActionPerformed(evt);
            }
        });
        jPDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPDVKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("PRODUTOS");

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("PRODUTO 1:");

        jProduto1.setText("Sandalia Havaianas");
        jProduto1.setToolTipText("INSIRA O NOME DO PRODUTO AQUI");
        jProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProduto1ActionPerformed(evt);
            }
        });
        jProduto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jProduto1KeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("CÓDIGO:");

        jCodigo1.setText("73845587774115");
        jCodigo1.setToolTipText("INSIRA O CÓDIGO AQUI");
        jCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigo1ActionPerformed(evt);
            }
        });
        jCodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCodigo1KeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("QTD:");

        jQTD1.setText("1");
        jQTD1.setToolTipText("");
        jQTD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQTD1ActionPerformed(evt);
            }
        });
        jQTD1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jQTD1KeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("VALOR UNI:");

        jLabel17.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("PRODUTO 2:");

        jProduto2.setToolTipText("INSIRA O NOME DO PRODUTO AQUI");
        jProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProduto2ActionPerformed(evt);
            }
        });
        jProduto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jProduto2KeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("CÓDIGO:");

        jCodigo2.setToolTipText("INSIRA O CÓDIGO AQUI");
        jCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigo2ActionPerformed(evt);
            }
        });
        jCodigo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCodigo2KeyReleased(evt);
            }
        });

        jQTD2.setToolTipText("");
        jQTD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQTD2ActionPerformed(evt);
            }
        });
        jQTD2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jQTD2KeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("QTD:");

        jLabel20.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("VALOR UNI:");

        jLabel21.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("PRODUTO 3:");

        jProduto3.setToolTipText("INSIRA O NOME DO PRODUTO AQUI");
        jProduto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProduto3ActionPerformed(evt);
            }
        });
        jProduto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jProduto3KeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("CÓDIGO:");

        jCodigo3.setToolTipText("INSIRA O CÓDIGO AQUI");
        jCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigo3ActionPerformed(evt);
            }
        });
        jCodigo3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCodigo3KeyReleased(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("QTD:");

        jQTD3.setToolTipText("");
        jQTD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQTD3ActionPerformed(evt);
            }
        });
        jQTD3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jQTD3KeyReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("VALOR UNI:");

        jLabel25.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("PRODUTO 4:");

        jProduto4.setToolTipText("INSIRA O NOME DO PRODUTO AQUI");
        jProduto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProduto4ActionPerformed(evt);
            }
        });
        jProduto4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jProduto4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jProduto4KeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("CÓDIGO:");

        jCodigo4.setToolTipText("INSIRA O CÓDIGO AQUI");
        jCodigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigo4ActionPerformed(evt);
            }
        });
        jCodigo4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCodigo4KeyReleased(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("QTD:");

        jQTD4.setToolTipText("");
        jQTD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQTD4ActionPerformed(evt);
            }
        });
        jQTD4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jQTD4KeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("VALOR UNI:");

        jLabel29.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("PRODUTO 5:");

        jProduto5.setToolTipText("INSIRA O NOME DO PRODUTO AQUI");
        jProduto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProduto5ActionPerformed(evt);
            }
        });
        jProduto5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jProduto5KeyReleased(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("CÓDIGO:");

        jCodigo5.setToolTipText("INSIRA O CÓDIGO AQUI");
        jCodigo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigo5ActionPerformed(evt);
            }
        });
        jCodigo5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCodigo5KeyReleased(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("QTD:");

        jQTD5.setToolTipText("");
        jQTD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQTD5ActionPerformed(evt);
            }
        });
        jQTD5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jQTD5KeyReleased(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("VALOR UNI:");

        jButtonLimpar.setBackground(new java.awt.Color(255, 204, 51));
        jButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonGerar.setBackground(new java.awt.Color(51, 102, 255));
        jButtonGerar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerar.setText("GERAR");
        jButtonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarActionPerformed(evt);
            }
        });

        jValor1.setText("15.90");
        jValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor1ActionPerformed(evt);
            }
        });
        jValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jValor1KeyReleased(evt);
            }
        });

        jValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor2ActionPerformed(evt);
            }
        });
        jValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jValor2KeyReleased(evt);
            }
        });

        jValor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor4ActionPerformed(evt);
            }
        });
        jValor4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jValor4KeyReleased(evt);
            }
        });

        jValor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor3ActionPerformed(evt);
            }
        });
        jValor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jValor3KeyReleased(evt);
            }
        });

        jValor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor5ActionPerformed(evt);
            }
        });
        jValor5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jValor5KeyReleased(evt);
            }
        });

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dev/imagens/linkedinTD1.png"))); // NOI18N
        jLabel36.setText("/WESLEIPOZARJOB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jQTD3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jValor3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jQTD2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jValor2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jQTD1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jValor1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jQTD5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel32)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jValor5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jQTD4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jValor4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                            .addComponent(jCPF))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel6)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jNcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jData, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(376, 376, 376))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(323, 323, 323))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jNcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jCupom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jQTD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jQTD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jQTD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jValor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jQTD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jValor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jQTD5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jValor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 51, 880, 520));

        jLabel34.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel34.setText("FORMULÁRIO DE TROCA E DEVOLUÇÃO");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 540, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dev/imagens/linkedinTD.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCupomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCupomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCupomActionPerformed

    private void jDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataActionPerformed

    private void jNcasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNcasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNcasaActionPerformed

    private void jCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCEPActionPerformed

    private void jPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPDVActionPerformed

    private void jProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProduto1ActionPerformed

    private void jCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigo1ActionPerformed

    private void jQTD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQTD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQTD1ActionPerformed

    private void jProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProduto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProduto2ActionPerformed

    private void jCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigo2ActionPerformed

    private void jQTD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQTD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQTD2ActionPerformed

    private void jProduto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProduto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProduto3ActionPerformed

    private void jCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigo3ActionPerformed

    private void jQTD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQTD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQTD3ActionPerformed

    private void jProduto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProduto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProduto4ActionPerformed

    private void jCodigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigo4ActionPerformed

    private void jQTD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQTD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQTD4ActionPerformed

    private void jProduto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProduto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProduto5ActionPerformed

    private void jCodigo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigo5ActionPerformed

    private void jQTD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQTD5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQTD5ActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
jCEP.setText("");
    jCPF.setText("");
    jCodigo1.setText("");
    jCodigo2.setText("");
    jCodigo3.setText("");
    jCodigo4.setText("");
    jCodigo5.setText("");
    jCupom.setText("");
    jData.setText("");
    jNcasa.setText("");
    jNome.setText("");
    jPDV.setText("");
    jProduto1.setText("");
    jProduto2.setText("");
    jProduto3.setText("");
    jProduto4.setText("");
    jProduto5.setText("");
    jQTD1.setText("");
    jQTD2.setText("");
    jQTD3.setText("");
    jQTD4.setText("");
    jQTD5.setText("");
    jTelefone.setText("");
    jValor1.setText("");
    jValor2.setText("");
    jValor3.setText("");
    jValor4.setText("");
    jValor5.setText("");       
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarActionPerformed
  if (jNome.getText().isEmpty() || jCEP.getText().isEmpty() || jCPF.getText().isEmpty() || jCupom.getText().isEmpty() || jTelefone.getText().isEmpty() || jData.getText().isEmpty() || jPDV.getText().isEmpty() || jNcasa.getText().isEmpty() || jProduto1.getText().isEmpty() || jQTD1.getText().isEmpty() || jValor1.getText().isEmpty()) {
      ImageIcon icon = new ImageIcon("C:\\devolucaoTroca\\src\\dev\\imagens");
    JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Campos vazios", JOptionPane.WARNING_MESSAGE);
} else {
    String Nome = jNome.getText();
    String Cpf = jCPF.getText();
    String Cep = jCEP.getText();
    String Tel = jTelefone.getText();
    String Data = jData.getText();
    String Cupom = jCupom.getText();
    String Pdv = jPDV.getText();
    String Ncasa = jNcasa.getText();
    String Prod1 = jProduto1.getText();
    String Qtd1 = jQTD1.getText();
    String Va1or1 = jValor1.getText();
    String Produto1 = jProduto1.getText();
    String Produto2 = jProduto2.getText();
    String Codigo1 = jCodigo1.getText();
    String Codigo2 = jCodigo2.getText();
    String Produto3 = jProduto3.getText();
    String Produto4 = jProduto4.getText();
    String Codigo3 = jCodigo3.getText();
    String Codigo4 = jCodigo4.getText();
    String Produto5 = jProduto5.getText();
    String Codigo5 = jCodigo5.getText();
    int quantidade1 = 0;
    int quantidade2 = 0;
    int quantidade3 = 0;
    int quantidade4 = 0;
    int quantidade5 = 0;
    double valorUnitario1 = 0.00;
    double valorUnitario2 = 0.00;
    double valorUnitario3 = 0.00;
    double valorUnitario4 = 0.00;
    double valorUnitario5 = 0.00;
    double total1 = 0.00;
    double total2 = 0.00;
    double total3 = 0.00;
    double total4 = 0.00;
    double total5 = 0.00;
    double resultadoFinal = 0.00;
    String resultadoFormatado = "";
    
    LocalDate dataAtual = LocalDate.now();

// Adicionando um mês à data atual
// Obtendo a data do campo jData como LocalDate
            String dataTexto = jData.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate data = LocalDate.parse(dataTexto, formatter);

            // Adicionando um mês à data atual
            LocalDate dataValidade = data.plusMonths(1);

            // Formatando a data para exibição
            
String dataValidadeFormatada = dataValidade.format(formatter);
    DecimalFormat decimalFormat = new DecimalFormat("0.00");
    if (!jQTD1.getText().isEmpty()&&!jProduto1.getText().isEmpty()&&!jCodigo1.getText().isEmpty()&&!jValor1.getText().isEmpty()) {
        quantidade1 = Integer.parseInt(jQTD1.getText());
        valorUnitario1 = Double.parseDouble(jValor1.getText());
        total1 = quantidade1 * valorUnitario1;
    }else{
         JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Campos vazios", JOptionPane.WARNING_MESSAGE);
    }
    if (!jQTD2.getText().isEmpty()) {
        quantidade2 = Integer.parseInt(jQTD2.getText());
        valorUnitario2 = Double.parseDouble(jValor2.getText());
        total2 = quantidade2 * valorUnitario2;
    }

    if (!jQTD3.getText().isEmpty()) {
        quantidade3 = Integer.parseInt(jQTD3.getText());
        valorUnitario3 = Double.parseDouble(jValor3.getText());
        total3 = quantidade3 * valorUnitario3;
    }

    if (!jQTD4.getText().isEmpty()) {
        quantidade4 = Integer.parseInt(jQTD4.getText());
        valorUnitario4 = Double.parseDouble(jValor4.getText());
        total4 = quantidade4 * valorUnitario4;
    }

    if (!jQTD5.getText().isEmpty()) {
        quantidade5 = Integer.parseInt(jQTD5.getText());
        valorUnitario5 = Double.parseDouble(jValor5.getText());
        total5 = quantidade5 * valorUnitario5;
    }

    if (!jProduto2.getText().isEmpty()) {
    if (!jProduto3.getText().isEmpty()) {
        if (!jProduto4.getText().isEmpty()) {
            if (!jProduto5.getText().isEmpty()) {
                resultadoFinal = total1 + total2 + total3 + total4 + total5;
                
            } else {
                resultadoFinal = total1 + total2 + total3 + total4;
            }
        } else {
            resultadoFinal = total1 + total2 + total3;
        }
    } else {
        resultadoFinal = total1 + total2;
    }
} else {
    resultadoFinal = total1;
}


//Formatando os valores
       resultadoFormatado = decimalFormat.format(resultadoFinal);
     
    String resultadoTotal1 = decimalFormat.format(total1);
    String resultadoTotal2 = decimalFormat.format(total2);
    String resultadoTotal3 = decimalFormat.format(total3);
    String resultadoTotal4 = decimalFormat.format(total4);
    String resultadoTotal5 = decimalFormat.format(total5);
    
    String valorU1 = decimalFormat.format(valorUnitario1);
    String valorU2 = decimalFormat.format(valorUnitario2);
    String valorU3 = decimalFormat.format(valorUnitario3);
    String valorU4 = decimalFormat.format(valorUnitario4);
    String valorU5 = decimalFormat.format(valorUnitario5);
    
    //O que irá aparecer na impressão
String linhaC = "-".repeat(70); // Caractere Unicode para um traço contínuo (—)
StringBuilder fraseBuilder = new StringBuilder();

fraseBuilder.append(linhaC)
        .append("\n               Atakarejo - Loja 01\n")
        .append(linhaC)
        .append("\n             Comprovante de devolucao\n")
        
        .append(linhaC)
        .append("\n");

// Adicionar informações apenas se o campo Nome estiver preenchido
if (!jNome.getText().isEmpty()) {
    fraseBuilder.append("Cliente  : ").append(Nome).append("\n");
}

// Adicionar informações apenas se o campo Cpf estiver preenchido
if (!jCPF.getText().isEmpty()) {
    fraseBuilder.append("CPF     : ").append(Cpf).append("\n");
}

// Adicionar informações apenas se o campo Cep estiver preenchido
if (!jCEP.getText().isEmpty()) {
    fraseBuilder.append("CEP     : ").append(Cep).append("\n");
}

// Adicionar informações apenas se o campo Tel estiver preenchido
if (!jTelefone.getText().isEmpty()) {
    fraseBuilder.append("Telefone: ").append(Tel).append("\n");
}

// Adicionar informações apenas se o campo Ncasa estiver preenchido
if (!jNcasa.getText().isEmpty()) {
    fraseBuilder.append("N°        : ").append(Ncasa).append("\n");
}

// Adicionar informações apenas se o campo Data estiver preenchido
if (!jData.getText().isEmpty()) {
    fraseBuilder.append("Data   : ").append(Data).append("   ");
}

// Adicionar informações apenas se o campo Pdv estiver preenchido
if (!jPDV.getText().isEmpty()) {
    fraseBuilder.append("PDV : ").append(Pdv).append("   ");
}

// Adicionar informações apenas se o campo Cupom estiver preenchido
if (!jCupom.getText().isEmpty()) {
    fraseBuilder.append("Cupom : ").append(Cupom).append("\n");
}

fraseBuilder.append(linhaC)
        .append("\nCod     Produto\n")
        .append("                     Qtd     Valor Uni     Total\n")
        .append("--").append(linhaC).append("\n")
        .append(dataValidadeFormatada).append("\n");

// Adicionar informações apenas se o campo Produto1 estiver preenchido
if (!jProduto1.getText().isEmpty()) {
    fraseBuilder.append(Produto1).append("\nC:").append(Codigo1)
            .append("\n                      ").append(quantidade1)
            .append("          R$").append(valorU1)
            .append("      R$").append(resultadoTotal1).append("\n")
            ;
}

// Adicionar informações apenas se o campo Produto2 estiver preenchido
if (!jProduto2.getText().isEmpty()) {
    fraseBuilder.append(Produto2).append("\nC:").append(Codigo2)
            .append("\n                      ").append(quantidade2)
            .append("          R$").append(valorU2)
            .append("      R$").append(resultadoTotal2).append("\n");
           
}

// Adicionar informações apenas se o campo Produto3 estiver preenchido
if (!jProduto3.getText().isEmpty()) {
    fraseBuilder.append(Produto3).append("\nC:").append(Codigo3)
            .append("\n                      ").append(quantidade3)
            .append("          R$").append(valorU3)
            .append("      R$").append(resultadoTotal3).append("\n")
            ;
}

// Adicionar informações apenas se o campo Produto4 estiver preenchido
if (!jProduto4.getText().isEmpty()) {
    fraseBuilder.append(Produto4).append("\nC:").append(Codigo4)
            .append("\n                      ").append(quantidade4)
            .append("          R$").append(valorU4)
            .append("      R$").append(resultadoTotal4).append("\n")
            ;
}

// Adicionar informações apenas se o campo Produto5 estiver preenchido
if (!jProduto5.getText().isEmpty()) {
    fraseBuilder.append(Produto5).append("\nC:").append(Codigo5)
            .append("\n                      ").append(quantidade5)
            .append("          R$").append(valorU5)
            .append("      R$").append(resultadoTotal5).append("\n")
            ;
}

fraseBuilder.append(linhaC)
        .append("\nTOTAL DA DEVOLUCAO: R$").append(resultadoFormatado).append("\n")
        .append(linhaC)
        .append("\n")
        .append("\n")
        .append(linhaC)
        .append("\n ATENDENTE SAC\n")
        .append("\n")
        .append(linhaC)
        .append("\n LIDER DE ATENDIMENTO\n")
        .append("\n")
        .append(linhaC)
        .append("\n PREVENCAO DE PERDAS\n")
        .append("\n")
        .append(linhaC)
        .append("\n CLIENTE\n")
        .append("\n")
        .append("\n")
        .append("\n Validade:\n")
        .append(dataValidadeFormatada).append("\n");
        
String frase = fraseBuilder.toString();

Impressao projeto = new Impressao(frase);
  ImageIcon icon = new ImageIcon("C:\\devolucaoTroca\\src\\dev\\imagens\\verificado.png");
JOptionPane.showMessageDialog(null, "Devolução feita com sucesso", "Aguarde impressão...", JOptionPane.WARNING_MESSAGE, icon);
System.out.println(dataValidadeFormatada);



  
}
     

    }//GEN-LAST:event_jButtonGerarActionPerformed

    private void jCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCPFActionPerformed

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
      
    }//GEN-LAST:event_jNomeActionPerformed

    private void jValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValor1ActionPerformed

    private void jValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValor2ActionPerformed

    private void jValor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValor4ActionPerformed

    private void jValor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValor3ActionPerformed

    private void jValor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValor5ActionPerformed

    private void jValor1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValor1KeyReleased
       jValor1.setText(jValor1.getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jValor1KeyReleased

    private void jValor2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValor2KeyReleased
        jValor2.setText(jValor2.getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jValor2KeyReleased

    private void jValor3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValor3KeyReleased
        jValor3.setText(jValor3.getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jValor3KeyReleased

    private void jValor4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValor4KeyReleased
         jValor4.setText(jValor4.getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jValor4KeyReleased

    private void jValor5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValor5KeyReleased
         jValor5.setText(jValor5.getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jValor5KeyReleased

    private void jQTD1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQTD1KeyReleased
        jQTD1.setText(jQTD1
                .getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jQTD1KeyReleased

    private void jQTD2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQTD2KeyReleased
      jQTD2.setText(jQTD2
                .getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jQTD2KeyReleased

    private void jQTD3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQTD3KeyReleased
        jQTD3.setText(jQTD3
                .getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jQTD3KeyReleased

    private void jQTD4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQTD4KeyReleased
        jQTD4.setText(jQTD4
                .getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jQTD4KeyReleased

    private void jQTD5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQTD5KeyReleased
    jQTD5.setText(jQTD5
                .getText().replaceAll("[^0-9|^.]", ""));
    }//GEN-LAST:event_jQTD5KeyReleased

    private void jCodigo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCodigo1KeyReleased
       jCodigo1.setText(jCodigo1
                .getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jCodigo1KeyReleased

    private void jCodigo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCodigo2KeyReleased
         jCodigo2.setText(jCodigo2
                .getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jCodigo2KeyReleased

    private void jCodigo3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCodigo3KeyReleased
         jCodigo3.setText(jCodigo3
                .getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jCodigo3KeyReleased

    private void jCodigo4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCodigo4KeyReleased
         jCodigo4.setText(jCodigo4
                .getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jCodigo4KeyReleased

    private void jCodigo5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCodigo5KeyReleased
         jCodigo5.setText(jCodigo5
                .getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jCodigo5KeyReleased

    private void jProduto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProduto1KeyReleased
        jProduto1.setText(jProduto1.getText().replaceAll("[^a-zA-Z\\s]", ""));
    }//GEN-LAST:event_jProduto1KeyReleased

    private void jProduto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProduto2KeyReleased
       jProduto2.setText(jProduto2.getText().replaceAll("[^a-zA-Z\\s]", ""));
    }//GEN-LAST:event_jProduto2KeyReleased

    private void jProduto3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProduto3KeyReleased
         jProduto3.setText(jProduto3.getText().replaceAll("[^a-zA-Z\\s]", ""));
    }//GEN-LAST:event_jProduto3KeyReleased

    private void jProduto4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProduto4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jProduto4KeyTyped

    private void jProduto4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProduto4KeyReleased
         jProduto4.setText(jProduto4.getText().replaceAll("[^a-zA-Z\\s]", ""));
    }//GEN-LAST:event_jProduto4KeyReleased

    private void jProduto5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProduto5KeyReleased
         jProduto5.setText(jProduto5.getText().replaceAll("[^a-zA-Z\\s]", ""));
    }//GEN-LAST:event_jProduto5KeyReleased

    private void jNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNomeKeyReleased
         jNome.setText(jNome.getText().replaceAll("[^a-zA-Z\\s]", ""));
    }//GEN-LAST:event_jNomeKeyReleased

    private void jCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCPFKeyReleased
         jCPF.setText(jCPF
                .getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jCPFKeyReleased

    private void jNcasaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNcasaKeyReleased
         jNcasa.setText(jNcasa
                .getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jNcasaKeyReleased

    private void jPDVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPDVKeyReleased
        jPDV.setText(jPDV
                .getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_jPDVKeyReleased
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonGerar;
    public javax.swing.JButton jButtonLimpar;
    public javax.swing.JFormattedTextField jCEP;
    public javax.swing.JFormattedTextField jCPF;
    public javax.swing.JTextField jCodigo1;
    public javax.swing.JTextField jCodigo2;
    public javax.swing.JTextField jCodigo3;
    public javax.swing.JTextField jCodigo4;
    public javax.swing.JTextField jCodigo5;
    public javax.swing.JFormattedTextField jCupom;
    public javax.swing.JFormattedTextField jData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JFormattedTextField jNcasa;
    public javax.swing.JTextField jNome;
    public javax.swing.JFormattedTextField jPDV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField jProduto1;
    public javax.swing.JTextField jProduto2;
    public javax.swing.JTextField jProduto3;
    public javax.swing.JTextField jProduto4;
    public javax.swing.JTextField jProduto5;
    public javax.swing.JTextField jQTD1;
    public javax.swing.JTextField jQTD2;
    public javax.swing.JTextField jQTD3;
    public javax.swing.JTextField jQTD4;
    public javax.swing.JTextField jQTD5;
    public javax.swing.JFormattedTextField jTelefone;
    public javax.swing.JTextField jValor1;
    public javax.swing.JTextField jValor2;
    public javax.swing.JTextField jValor3;
    public javax.swing.JTextField jValor4;
    public javax.swing.JTextField jValor5;
    // End of variables declaration//GEN-END:variables

    public Object JTextFieldQTD1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getJTextFieldQTD1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getJFormattedTextFieldValor1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
